name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install System Packages
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip wget \
            openjdk-17-jdk \
            build-essential \
            libffi-dev \
            libssl-dev \
            libtinfo6 \
            libncurses6 \
            libjpeg-dev

      - name: Set Java
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH" >> $GITHUB_ENV

      - name: Install Python Tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython
          pip install kivy==2.2.1
          pip install python-bidi==0.4.2
          pip install arabic-reshaper
          pip install openpyxl
          pip install plyer

      - name: Clean Build Cache
        run: |
          rm -rf .buildozer
          rm -rf ~/.buildozer
          mkdir -p ~/.buildozer

      # ✅ مهم: فقط ARM64 بساز
      - name: Build APK (ARM64 Only)
        run: |
          yes | buildozer android debug \
            --arch=arm64-v8a \
            --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: bin/*.apk
